//! R2b Task 2 — L3 call-graph SCALAR-PRIMITIVE vector parity.
//!
//! Loads the committed `tests/r2b-vectors/l3cg-vectors.json` (generated by the
//! REAL exported al-sem primitives in `src/resolve/call-resolver.ts` +
//! `src/resolve/type-ref.ts`) and asserts the Rust ports of the PURE scalar
//! string/type functions reproduce each vector EXACTLY.
//!
//! Scope (this task): the seven scalar-primitive families only —
//!   normalizeAlType, typeRelation, scalarFamily, isObjectish, isEnumish,
//!   parseObjectTypeRef, simpleReceiverName.
//! The 19 RESOLUTION vectors (`resolutionVectors`) are Task 3 — they are NOT
//! exercised here, but the full JSON stays committed.
//!
//! The vectors are the oracle: a failure means the Rust port diverged from
//! al-sem, and the fix is in the Rust code (never the vector).

use al_call_hierarchy::engine::l3::al_type::normalize_al_type;
use al_call_hierarchy::engine::l3::receiver::simple_receiver_name;
use al_call_hierarchy::engine::l3::type_ref::{parse_object_type_ref, ObjectTypeRef};
use al_call_hierarchy::engine::l3::type_rel::{
    is_enumish, is_objectish, scalar_family, type_relation,
};

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "scalarVectorCount")]
    scalar_vector_count: usize,
    #[serde(rename = "scalarVectors")]
    scalar_vectors: ScalarVectors,
}

#[derive(serde::Deserialize)]
struct ScalarVectors {
    #[serde(rename = "normalizeAlType")]
    normalize_al_type: Vec<InputExpected<String>>,
    #[serde(rename = "typeRelation")]
    type_relation: Vec<TypeRelationVec>,
    #[serde(rename = "scalarFamily")]
    scalar_family: Vec<InputExpected<Option<String>>>,
    #[serde(rename = "isObjectish")]
    is_objectish: Vec<InputExpected<bool>>,
    #[serde(rename = "isEnumish")]
    is_enumish: Vec<InputExpected<bool>>,
    #[serde(rename = "parseObjectTypeRef")]
    parse_object_type_ref: Vec<InputExpected<Option<ExpectedRef>>>,
    #[serde(rename = "simpleReceiverName")]
    simple_receiver_name: Vec<InputExpected<Option<String>>>,
}

#[derive(serde::Deserialize)]
struct InputExpected<T> {
    input: String,
    expected: T,
}

#[derive(serde::Deserialize)]
struct TypeRelationVec {
    #[serde(rename = "argType")]
    arg_type: String,
    #[serde(rename = "paramType")]
    param_type: String,
    expected: String,
}

#[derive(serde::Deserialize)]
struct ExpectedRef {
    kind: String,
    name: String,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("r2b-vectors/l3cg-vectors.json");
    serde_json::from_str(raw).expect("l3cg-vectors.json parses into VectorsDoc")
}

#[test]
fn all_scalar_primitive_vectors_match() {
    let doc = load_vectors();
    let sv = &doc.scalar_vectors;

    let mut failures: Vec<String> = Vec::new();
    let mut checked = 0usize;

    // ---- normalizeAlType ----
    for v in &sv.normalize_al_type {
        checked += 1;
        let actual = normalize_al_type(&v.input);
        if actual != v.expected {
            failures.push(format!(
                "normalizeAlType({:?}): expected {:?}, actual {:?}",
                v.input, v.expected, actual
            ));
        }
    }

    // ---- typeRelation ----
    for v in &sv.type_relation {
        checked += 1;
        let actual = type_relation(&v.arg_type, &v.param_type);
        let actual_str = actual.as_str();
        if actual_str != v.expected {
            failures.push(format!(
                "typeRelation({:?}, {:?}): expected {:?}, actual {:?}",
                v.arg_type, v.param_type, v.expected, actual_str
            ));
        }
    }

    // ---- scalarFamily (expected may be null) ----
    for v in &sv.scalar_family {
        checked += 1;
        let actual = scalar_family(&v.input);
        let actual_opt = actual.map(|s| s.to_string());
        if actual_opt != v.expected {
            failures.push(format!(
                "scalarFamily({:?}): expected {:?}, actual {:?}",
                v.input, v.expected, actual_opt
            ));
        }
    }

    // ---- isObjectish ----
    for v in &sv.is_objectish {
        checked += 1;
        let actual = is_objectish(&v.input);
        if actual != v.expected {
            failures.push(format!(
                "isObjectish({:?}): expected {}, actual {}",
                v.input, v.expected, actual
            ));
        }
    }

    // ---- isEnumish ----
    for v in &sv.is_enumish {
        checked += 1;
        let actual = is_enumish(&v.input);
        if actual != v.expected {
            failures.push(format!(
                "isEnumish({:?}): expected {}, actual {}",
                v.input, v.expected, actual
            ));
        }
    }

    // ---- parseObjectTypeRef (expected may be null) ----
    for v in &sv.parse_object_type_ref {
        checked += 1;
        let actual = parse_object_type_ref(&v.input);
        let ok = match (&actual, &v.expected) {
            (None, None) => true,
            (Some(ObjectTypeRef { kind, name }), Some(exp)) => {
                kind.as_str() == exp.kind && name == &exp.name
            }
            _ => false,
        };
        if !ok {
            let exp_str = v
                .expected
                .as_ref()
                .map(|e| format!("{}/{}", e.kind, e.name));
            let act_str = actual
                .as_ref()
                .map(|r| format!("{}/{}", r.kind.as_str(), r.name));
            failures.push(format!(
                "parseObjectTypeRef({:?}): expected {:?}, actual {:?}",
                v.input, exp_str, act_str
            ));
        }
    }

    // ---- simpleReceiverName (expected may be null) ----
    for v in &sv.simple_receiver_name {
        checked += 1;
        let actual = simple_receiver_name(&v.input);
        if actual != v.expected {
            failures.push(format!(
                "simpleReceiverName({:?}): expected {:?}, actual {:?}",
                v.input, v.expected, actual
            ));
        }
    }

    assert_eq!(
        checked, doc.scalar_vector_count,
        "checked vector count must equal the declared scalarVectorCount"
    );

    assert!(
        failures.is_empty(),
        "L3 scalar-primitive vector parity failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n")
    );
}
