//! R2d Task 2 — L3 COVERAGE vector parity.
//!
//! Loads the committed `tests/r2d-vectors/l3cov-vectors.json` (generated by the
//! real al-sem L3: `indexWorkspace` pre-resolve → `resolveModel` post-resolve/
//! pre-summary → projectL3Coverage; READ-ONLY, never re-runs buildCoverage) and
//! asserts the Rust `build_coverage` reproduces al-sem's `AnalysisCoverage`
//! EXACTLY for three vector families:
//!
//!   (a) COVERAGE vectors — assemble + resolve the inline workspace, then
//!       `project_coverage` (the SAME post-resolve read the dump uses) and compare
//!       the projected `AnalysisCoverage` to `expected`. Covers routine counts,
//!       bodyAvailable, the 4 unresolved resolutions (unknown / ambiguous /
//!       member-not-found / external-target) AND the negatives (builtin / opaque /
//!       resolved NOT counted), dynamic dispatch, parse-incomplete, opaqueApps empty.
//!
//!   (b) WARNING-UNPARSED-UNIT — an empty `.al` unit produces an index-stage WARNING
//!       whose `sourceRef === unit.id` → `sourceUnitsParsed = total - 1`. The vector
//!       supplies al-sem's EXACT diagnostic triple + the unit list; `build_coverage`
//!       keys ONLY on (stage:"index", severity:"warning", sourceRef===unit.id), so
//!       the Rust decrement reproduces it. (This is the ONLY vector that exercises
//!       the decrement; the corpus is inert.)
//!
//!   (c) MULTISET-DUPLICATE (SYNTHETIC) — a hand-built call graph fed to the REAL
//!       `build_coverage` proves the sorted MULTISET PRESERVES duplicates (cs0 twice,
//!       op9 twice) and the 4-resolutions filter EXCLUDES maybe / opaque / builtin /
//!       resolved. The ids are already stable (`r0/deadbeef/...`), so the stable map
//!       is empty (prefix kept verbatim).
//!
//! The vectors are the oracle: a failure means the Rust port diverged from al-sem,
//! and the fix is in the Rust code (never the vector).
//!
//! Reproduction context (from `scripts/gen-l3cov-vectors.ts`):
//!   - appGuid          = "2d000000-0000-0000-0000-0000000002dd"
//!   - modelInstanceId  = "r0"
//!   - files            = [[name, source], ...]  →  sourceUnitId = "ws:<name>"

use std::collections::HashMap;

use al_call_hierarchy::engine::l3::call_resolver::{CallEdge, UnknownReason};
use al_call_hierarchy::engine::l3::coverage::{
    build_coverage, AnalysisCoverage, CoverageDiagnostic, CoverageUnit,
};
use al_call_hierarchy::engine::l3::l3_workspace::assemble_and_resolve;
use al_call_hierarchy::engine::l3::taxonomy::{DispatchKind, Resolution};
use serde_json::Value;

const APP_GUID: &str = "2d000000-0000-0000-0000-0000000002dd";
const MODEL_INSTANCE_ID: &str = "r0";

// ---------------------------------------------------------------------------
// Vector document shapes (minimal — only the fields the test reads).
// ---------------------------------------------------------------------------

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "coverageVectorCount")]
    coverage_vector_count: usize,
    #[serde(rename = "coverageVectors")]
    coverage_vectors: Vec<CoverageVector>,
    #[serde(rename = "warningUnparsedVector")]
    warning_unparsed_vector: WarningUnparsedVector,
    #[serde(rename = "multisetDuplicateVector")]
    multiset_duplicate_vector: MultisetDuplicateVector,
}

#[derive(serde::Deserialize)]
struct CoverageVector {
    family: String,
    name: String,
    /// `[[filename, source], ...]`
    files: Vec<Vec<String>>,
    expected: Value,
}

#[derive(serde::Deserialize)]
struct WarningUnparsedVector {
    name: String,
    files: Vec<Vec<String>>,
    #[serde(rename = "indexDiagnostics")]
    index_diagnostics: Vec<VectorDiagnostic>,
    units: Vec<VectorUnit>,
    expected: Value,
}

#[derive(serde::Deserialize)]
struct VectorDiagnostic {
    severity: String,
    stage: String,
    #[serde(rename = "sourceRef")]
    source_ref: Option<String>,
}

#[derive(serde::Deserialize)]
struct VectorUnit {
    id: String,
    kind: String,
}

#[derive(serde::Deserialize)]
struct MultisetDuplicateVector {
    name: String,
    #[serde(rename = "callGraph")]
    call_graph: Vec<VectorEdge>,
    expected: Value,
}

/// The synthetic edge shape — already-stable ids + the resolution/dispatch fields.
#[derive(serde::Deserialize)]
struct VectorEdge {
    from: String,
    #[serde(rename = "callsiteId")]
    callsite_id: String,
    #[serde(rename = "operationId")]
    operation_id: String,
    #[serde(rename = "dispatchKind")]
    dispatch_kind: String,
    resolution: String,
}

/// Parse a golden `dispatchKind` wire string back into the strict enum.
fn dispatch_kind_from_wire(s: &str) -> DispatchKind {
    match s {
        "direct" => DispatchKind::Direct,
        "interface" => DispatchKind::Interface,
        "builtin" => DispatchKind::Builtin,
        "unresolved" => DispatchKind::Unresolved,
        "dynamic" => DispatchKind::Dynamic,
        "method" => DispatchKind::Method,
        "implicit-trigger" => DispatchKind::ImplicitTrigger,
        "page-run" => DispatchKind::PageRun,
        "report-run" => DispatchKind::ReportRun,
        "codeunit-run" => DispatchKind::CodeunitRun,
        other => panic!("unexpected dispatchKind in vector fixture: {other}"),
    }
}

/// Parse a golden `resolution` wire string back into the strict enum. `unknown`
/// folds an `UnknownReason`; the vectors carry no reason, so use `CalleeUnknown`.
fn resolution_from_wire(s: &str) -> Resolution {
    match s {
        "resolved" => Resolution::Resolved,
        "maybe" => Resolution::Maybe,
        "builtin" => Resolution::Builtin,
        "member-not-found" => Resolution::MemberNotFound,
        "ambiguous" => Resolution::Ambiguous,
        "opaque" => Resolution::Opaque,
        "external-target" => Resolution::ExternalTarget,
        "unknown" => Resolution::Unknown(UnknownReason::CalleeUnknown),
        other => panic!("unexpected resolution in vector fixture: {other}"),
    }
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("r2d-vectors/l3cov-vectors.json");
    serde_json::from_str(raw).expect("l3cov-vectors.json parses into VectorsDoc")
}

fn files_of(files: &[Vec<String>]) -> Vec<(String, String)> {
    files
        .iter()
        .map(|pair| {
            assert_eq!(pair.len(), 2, "each file entry is [name, source]");
            (pair[0].clone(), pair[1].clone())
        })
        .collect()
}

/// Build the implicit source-unit list for an inline workspace: one `ws:<name>`
/// `source` unit per file, matching al-sem's WorkspaceProvider unit ids.
fn units_of(files: &[Vec<String>]) -> Vec<CoverageUnit> {
    files
        .iter()
        .map(|pair| CoverageUnit {
            id: format!("ws:{}", pair[0]),
            kind: "source".to_string(),
        })
        .collect()
}

// ---------------------------------------------------------------------------
// (a) coverage vectors — full AnalysisCoverage parity over inline workspaces.
// ---------------------------------------------------------------------------

#[test]
fn all_coverage_vectors_match() {
    let doc = load_vectors();
    assert_eq!(
        doc.coverage_vector_count,
        doc.coverage_vectors.len(),
        "coverageVectorCount agrees with the array length"
    );

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.coverage_vectors {
        let files = files_of(&vec.files);
        let units = units_of(&vec.files);
        let no_diags: Vec<CoverageDiagnostic> = Vec::new();

        let resolved = assemble_and_resolve(&files, APP_GUID, MODEL_INSTANCE_ID);
        let coverage = resolved.project_coverage(&units, &no_diags);

        let actual = serde_json::to_value(&coverage).expect("AnalysisCoverage serializes");
        if actual != vec.expected {
            failures.push(format!(
                "[{}] {}: coverage mismatch\n  expected: {}\n  actual:   {}",
                vec.family,
                vec.name,
                serde_json::to_string_pretty(&vec.expected).unwrap(),
                serde_json::to_string_pretty(&actual).unwrap()
            ));
        }
    }

    assert!(
        failures.is_empty(),
        "coverage vector parity failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}

// ---------------------------------------------------------------------------
// (b) warning-unparsed-unit — the sourceUnitsParsed decrement.
// ---------------------------------------------------------------------------

#[test]
fn warning_unparsed_vector_decrements() {
    let doc = load_vectors();
    let v = &doc.warning_unparsed_vector;

    let files = files_of(&v.files);
    // Use the vector's EXPLICIT unit list (id + kind) — the warning's sourceRef
    // points at one of these ids.
    let units: Vec<CoverageUnit> = v
        .units
        .iter()
        .map(|u| CoverageUnit {
            id: u.id.clone(),
            kind: u.kind.clone(),
        })
        .collect();
    let diagnostics: Vec<CoverageDiagnostic> = v
        .index_diagnostics
        .iter()
        .map(|d| CoverageDiagnostic {
            stage: d.stage.clone(),
            severity: d.severity.clone(),
            source_ref: d.source_ref.clone(),
        })
        .collect();

    let resolved = assemble_and_resolve(&files, APP_GUID, MODEL_INSTANCE_ID);
    let coverage = resolved.project_coverage(&units, &diagnostics);
    let actual = serde_json::to_value(&coverage).expect("serialize");

    assert_eq!(
        actual,
        v.expected,
        "[{}] warning-unparsed coverage mismatch\n  expected: {}\n  actual:   {}",
        v.name,
        serde_json::to_string_pretty(&v.expected).unwrap(),
        serde_json::to_string_pretty(&actual).unwrap()
    );

    // Spell out the decrement invariant explicitly.
    let exp: AnalysisCoverage = serde_json::from_value(v.expected.clone()).expect("parse expected");
    assert_eq!(exp.source_units_total, 2, "two source units");
    assert_eq!(
        exp.source_units_parsed, 1,
        "the empty unit's index-stage warning decremented sourceUnitsParsed"
    );
    assert_eq!(coverage.source_units_parsed, exp.source_units_parsed);
}

// ---------------------------------------------------------------------------
// (c) multiset-duplicate (synthetic) — preserve duplicates; 4-resolutions filter.
// ---------------------------------------------------------------------------

#[test]
fn multiset_duplicate_vector_preserves_dups() {
    let doc = load_vectors();
    let v = &doc.multiset_duplicate_vector;

    // Build CallEdges directly from the synthetic graph (ids are ALREADY stable).
    let edges: Vec<CallEdge> = v
        .call_graph
        .iter()
        .map(|e| CallEdge {
            from: e.from.clone(),
            to: None,
            callsite_id: e.callsite_id.clone(),
            operation_id: e.operation_id.clone(),
            dispatch_kind: dispatch_kind_from_wire(&e.dispatch_kind),
            resolution: resolution_from_wire(&e.resolution),
            candidates: None,
            external_type_ref: None,
            receiver_type: None,
            dispatch_meta: None,
            unknown_method_name: None,
            receiver_shape: None,
        })
        .collect();

    // No routines / apps / units; empty stable map (prefixes already stable).
    let by_internal: HashMap<String, String> = HashMap::new();
    let coverage = build_coverage(&[], &[], &edges, &[], &[], &by_internal);

    let actual = serde_json::to_value(&coverage).expect("serialize");
    assert_eq!(
        actual,
        v.expected,
        "[{}] multiset coverage mismatch\n  expected: {}\n  actual:   {}",
        v.name,
        serde_json::to_string_pretty(&v.expected).unwrap(),
        serde_json::to_string_pretty(&actual).unwrap()
    );

    // Explicit multiset invariants (Rev 2 MUST-FIX #2).
    let cs0 = "r0/deadbeef/cs0";
    let dup_count = coverage
        .unresolved_callsites
        .iter()
        .filter(|s| s.as_str() == cs0)
        .count();
    assert_eq!(
        dup_count, 2,
        "cs0 appears EXACTLY twice (duplicate preserved)"
    );
    assert_eq!(
        coverage.unresolved_callsites.len(),
        4,
        "unresolved cardinality = 4 (cs0 twice + cs1 + cs2); maybe/opaque/builtin excluded"
    );
    let op9 = "r0/deadbeef/op9";
    let dyn_dup = coverage
        .dynamic_dispatch_sites
        .iter()
        .filter(|s| s.as_str() == op9)
        .count();
    assert_eq!(
        dyn_dup, 2,
        "op9 appears EXACTLY twice in dynamicDispatchSites"
    );
    assert_eq!(
        coverage.dynamic_dispatch_sites.len(),
        2,
        "two dynamic edges"
    );

    // Sorted assertion.
    let mut sorted = coverage.unresolved_callsites.clone();
    sorted.sort();
    assert_eq!(
        coverage.unresolved_callsites, sorted,
        "unresolvedCallsites is sorted"
    );
}
