//! R2a Task 2 — L3 record-type resolution vector parity.
//!
//! Loads the committed `tests/r2a-vectors/l3rt-vectors.json` (generated by the
//! real al-sem L3: `indexWorkspace` pre-resolve → `resolveModel` post-resolve/
//! pre-summary → projectL3RecordTypes) and asserts the Rust L3 foundation
//! (workspace symbol table + record-type resolution + extension-field merge)
//! reproduces each vector family's resolved `tableId` (StableTableId form, ABSENT
//! when unresolved) + merged extension fields EXACTLY.
//!
//! The vectors are the oracle: a failure means the Rust port diverged from
//! al-sem, and the fix is in the Rust code (never the vector).
//!
//! Reproduction context (from `scripts/gen-l3rt-vectors.ts`):
//!   - appGuid          = "2a000000-0000-0000-0000-0000000002aa"
//!   - modelInstanceId  = "r0"
//!   - files            = [[name, source], ...]  →  sourceUnitId = "ws:<name>"

use al_call_hierarchy::engine::l3::l3_workspace::assemble_and_resolve;

const APP_GUID: &str = "2a000000-0000-0000-0000-0000000002aa";
const MODEL_INSTANCE_ID: &str = "r0";

#[derive(serde::Deserialize)]
struct VectorsDoc {
    #[serde(rename = "familyCount")]
    family_count: usize,
    #[serde(rename = "vectorCount")]
    vector_count: usize,
    vectors: Vec<Vector>,
}

#[derive(serde::Deserialize)]
struct Vector {
    family: String,
    name: String,
    /// `[[filename, source], ...]`
    files: Vec<Vec<String>>,
    #[serde(rename = "routineName")]
    routine_name: Option<String>,
    #[serde(rename = "expectedRoutine")]
    expected_routine: Option<ExpectedRoutine>,
    #[serde(rename = "tableName")]
    table_name: Option<String>,
    #[serde(rename = "expectedTable")]
    expected_table: Option<ExpectedTable>,
}

#[derive(serde::Deserialize)]
struct ExpectedRoutine {
    #[serde(rename = "recordVariables")]
    record_variables: Vec<ExpectedRecordVar>,
    #[serde(rename = "recordOperations")]
    record_operations: Vec<ExpectedRecordOp>,
}

#[derive(serde::Deserialize)]
struct ExpectedRecordVar {
    name: String,
    #[serde(rename = "tableId")]
    table_id: Option<String>,
}

#[derive(serde::Deserialize)]
struct ExpectedRecordOp {
    op: String,
    #[serde(rename = "recordVariableName")]
    record_variable_name: String,
    #[serde(rename = "tableId")]
    table_id: Option<String>,
}

#[derive(serde::Deserialize)]
struct ExpectedTable {
    #[serde(rename = "stableTableId")]
    stable_table_id: String,
    fields: Vec<ExpectedField>,
}

#[derive(serde::Deserialize)]
struct ExpectedField {
    #[serde(rename = "fieldNumber")]
    field_number: i64,
    name: String,
    #[serde(rename = "dataType")]
    data_type: String,
    #[serde(rename = "fieldClass")]
    field_class: String,
    #[serde(rename = "declaringObjectId")]
    declaring_object_id: String,
}

fn load_vectors() -> VectorsDoc {
    let raw = include_str!("../r2a-vectors/l3rt-vectors.json");
    serde_json::from_str(raw).expect("l3rt-vectors.json parses into VectorsDoc")
}

fn files_of(vec: &Vector) -> Vec<(String, String)> {
    vec.files
        .iter()
        .map(|pair| {
            assert_eq!(pair.len(), 2, "each file entry is [name, source]");
            (pair[0].clone(), pair[1].clone())
        })
        .collect()
}

#[test]
fn all_l3rt_vector_families_match() {
    let doc = load_vectors();
    assert_eq!(doc.family_count, 12, "expected 12 vector families");
    assert_eq!(doc.vector_count, 12, "expected 12 vectors");

    let mut failures: Vec<String> = Vec::new();

    for vec in &doc.vectors {
        let files = files_of(vec);
        let resolved = assemble_and_resolve(&files, APP_GUID, MODEL_INSTANCE_ID);

        // ----- routine-shaped vector: assert record var / op tableIds -----
        if let (Some(rname), Some(exp)) = (&vec.routine_name, &vec.expected_routine) {
            let Some(routine) = resolved.routine_by_name(rname) else {
                failures.push(format!(
                    "[{}] {}: routine `{rname}` not found by the L3 assembly",
                    vec.family, vec.name
                ));
                continue;
            };

            // Record variables — compare resolved tableId (absent == None).
            for ev in &exp.record_variables {
                let actual = routine.record_var_table_id(&ev.name);
                if actual != ev.table_id {
                    failures.push(format!(
                        "[{}] {}: record var `{}` tableId mismatch\n  expected: {:?}\n  actual:   {:?}",
                        vec.family, vec.name, ev.name, ev.table_id, actual
                    ));
                }
            }
            // The L3 routine must carry exactly the expected number of record vars.
            if routine.record_var_count() != exp.record_variables.len() {
                failures.push(format!(
                    "[{}] {}: record var count mismatch (expected {}, actual {})",
                    vec.family,
                    vec.name,
                    exp.record_variables.len(),
                    routine.record_var_count()
                ));
            }

            // Record operations — positional (the vectors list ops in walk order).
            let actual_ops = routine.record_ops();
            if actual_ops.len() != exp.record_operations.len() {
                failures.push(format!(
                    "[{}] {}: record op count mismatch (expected {}, actual {})",
                    vec.family,
                    vec.name,
                    exp.record_operations.len(),
                    actual_ops.len()
                ));
            } else {
                for (i, eo) in exp.record_operations.iter().enumerate() {
                    let (op, rvn, tid) = &actual_ops[i];
                    if op != &eo.op
                        || rvn.to_lowercase() != eo.record_variable_name.to_lowercase()
                        || tid != &eo.table_id
                    {
                        failures.push(format!(
                            "[{}] {}: op[{i}] mismatch\n  expected: op={} var={} tableId={:?}\n  actual:   op={} var={} tableId={:?}",
                            vec.family, vec.name, eo.op, eo.record_variable_name, eo.table_id, op, rvn, tid
                        ));
                    }
                }
            }
            continue;
        }

        // ----- table-shaped vector: assert merged extension fields -----
        if let (Some(tname), Some(exp)) = (&vec.table_name, &vec.expected_table) {
            let Some(table) = resolved.table_by_name(tname) else {
                failures.push(format!(
                    "[{}] {}: table `{tname}` not found by the L3 assembly",
                    vec.family, vec.name
                ));
                continue;
            };
            if table.stable_table_id() != exp.stable_table_id {
                failures.push(format!(
                    "[{}] {}: stableTableId mismatch\n  expected: {}\n  actual:   {}",
                    vec.family,
                    vec.name,
                    exp.stable_table_id,
                    table.stable_table_id()
                ));
            }
            let actual_fields = table.merged_fields();
            if actual_fields.len() != exp.fields.len() {
                failures.push(format!(
                    "[{}] {}: merged field count mismatch (expected {}, actual {})\n  actual: {:?}",
                    vec.family,
                    vec.name,
                    exp.fields.len(),
                    actual_fields.len(),
                    actual_fields
                ));
            } else {
                for (i, ef) in exp.fields.iter().enumerate() {
                    let af = &actual_fields[i];
                    if af.field_number != ef.field_number
                        || af.name != ef.name
                        || af.data_type != ef.data_type
                        || af.field_class != ef.field_class
                        || af.declaring_object_id != ef.declaring_object_id
                    {
                        failures.push(format!(
                            "[{}] {}: field[{i}] mismatch\n  expected: #{} {} {} {} decl={}\n  actual:   #{} {} {} {} decl={}",
                            vec.family, vec.name,
                            ef.field_number, ef.name, ef.data_type, ef.field_class, ef.declaring_object_id,
                            af.field_number, af.name, af.data_type, af.field_class, af.declaring_object_id
                        ));
                    }
                }
            }
            continue;
        }

        failures.push(format!(
            "[{}] {}: vector is neither routine-shaped nor table-shaped",
            vec.family, vec.name
        ));
    }

    assert!(
        failures.is_empty(),
        "L3 record-type vector parity failures ({}):\n\n{}",
        failures.len(),
        failures.join("\n\n")
    );
}
